# Ogólne informacje o projekcie pobrane z SonarCloud
sonar.projectKey=Dud3q_budget-app
sonar.organization=dud3q
sonar.host.url=https://sonarcloud.io

# Definicja modułów dla monorepo
sonar.modules=backend,frontend

# Konfiguracja analizy dla Backend (Java)
backend.sonar.projectBaseDir=Backend
backend.sonar.sources=src/main/java
backend.sonar.java.binaries=target/classes

# Konfiguracja analizy dla Frontend (React / TypeScript)
frontend.sonar.projectBaseDir=Frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/*.spec.ts,**/*.test.tsx,**/__tests__/**

#Wykluczenie testów
sonar.coverage.exclusions=**/*